config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'pages#home'
  get '/settings', to: 'pages#settings'
  post '/settings', to: 'pages#toggle_voice', as: :toggle
  patch '/settings', to: 'pages#message', as: :message
  get '/get_help', to: 'pages#get_help', as: :get_help
  post '/get_help', to: 'pages#send_message', as: :send
  get '/dashboard', to: 'pages#dashboard'
  resources :contacts, only: [:edit, :update]
  # Error pages routes
  get '/404', to: "errors#not_found"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :message, presence: true, length: { minimum: 10 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :contacts
  has_many :sessions
  after_create :add_contacts

  private 
  # adds 3 template contacts to be filled/edited by the user upon registration
  def add_contacts
    id = self.id
    3.times do
      Contact.new(user_id: id).save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:message])
    devise_parameter_sanitizer.permit(:account_update, keys: [:message])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def update
    @contact = Contact.find(params[:id])
    @contact.update(contact_params)
    redirect_to settings_path, notice: "Updated contact details"
  end

  private
  
  def contact_params
    params.require(:contact).permit(:name, :phone_number)
  end
end

app/controllers/errors_controller.rb
# encoding: utf-8

class ErrorsController < ApplicationController
  skip_before_action :authenticate_user!

  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  end

  def unacceptable
    respond_to do |format|
      format.html { render status: 422 }
    end
  end

  def internal_error
    respond_to do |format|
      format.html { render status: 500 }
    end
  end
end

app/controllers/pages_controller.rb
require 'json'

class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [ :home ]
  before_action :set_sessions, only: [:home, :dashboard]
  before_action :set_contacts, only: [:settings, :get_help]
  

  def home
    #if user is logged in, save the session
    save_session if current_user
  end

  def settings
  end

  def get_help
  end

  def dashboard
  end

  # Message sent from Twilio to Valerias number
  def send_message
    message = "I'm having a panic attack. Please write me."
    TwilioTextMessenger.new(message).call
    redirect_to root_path, notice: "Message sent. Keep breathing."
  end

  def message
    current_user.message = params["/settings"][:message]
    if current_user.save
      redirect_to settings_path, notice: "Message updated succesfully"
    else
      redirect_to settings_path, alert: "Message must be min. 10 characters"
    end
  end

  def toggle_voice
    if current_user.voice == true
      current_user.voice = false
      current_user.save
      redirect_to settings_path
    else
      current_user.voice = true
      current_user.save
      redirect_to settings_path
    end
  end

  private

  def set_contacts
    @contacts = Contact.where(user_id: current_user.id)
  end

  def set_sessions
    @sessions = Session.where(user_id: current_user.id).sort_by &:created_at if current_user
  end


  def save_session
    #if its the first session or the last recorded sessions is
    #longer than 5 minutes ago, save a new session
    minduration = (Time.now - @sessions.last.created_at) > 300
    if @sessions.empty? || minduration
      new_sess = Session.new(user_id: current_user.id, time: Time.now)
      new_sess.save
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end
  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end
  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charlie</title>
    <%= favicon_link_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>

    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload", defer: true %>

  </head>

  <body>
    <% # <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= render "shared/logo" %>
  <div class="page-container">
    <div class="content-container"><%= yield %></div>
    <div class="footer-container"><%= render "shared/footer" %></div>
  </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="title">
   <h1 class="text-center">When do you need Charlie the most?</h1>
</div>
<div id="diagram">
  <%= column_chart Session.group_by_day_of_week(:created_at, format: "%a").count %>
</div>

<div class="btn-top">
  <%= link_to "Settings", settings_path, class:"settings-btn" %>
  <br>
  <div class="btn-top01">
  <%= link_to "Logout", destroy_user_session_path, method: :delete,  class:"mini-btn01" %>
  </div>
</div>

app/views/pages/get_help.html.erb
<div class="title">
  <h1 class="text-center">Reach out for help:</h1>
</div>
<div id="get-help-options">
  <% iter = 1 %>
    <% @contacts.each do |contact| %>
      <div class="card card-header" id="choice<%= iter %>"><%= contact.name == "" ? "Empty contact" : contact.name %></div>
      <% iter += 1 %>
    <% end %>
</div>
<%= link_to "Get Help", send_path, method: :post, class: "charliesBtn" %>

app/views/pages/home.html.erb
<div class="mobile-container">
  <!-- DEMO BUTTON -->
  <div class="bg-pulse" id="getdemo"> <a href="">?</a> </div>
  <p class="mobile-title">Breathe in. Breathe out. <br> Follow the pace.</p>
  <!-- BREATHING ANIMATION -->
  <div class="animation"></div>


  <?xml version="1.0" encoding="utf-8"?>
  <!-- FOG 1 -->
  <svg version="1.1" class="fog-1" id="Ebene_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 1920 1080" xml:space="preserve">
  <style type="text/css">
    .st0{fill:url(#SVGID_1_);}
  </style>
  <linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="960.1951" y1="205" x2="960.1951" y2="1080.2198">
    <stop  offset="0" style="stop-color:#F4F0F5"/>
    <stop  offset="1" style="stop-color:#F1E2E7"/>
  </linearGradient>
  <path class="st0" d="M1920,1080.2H0.4V205l0,0c139.2,40.7,288.4,46.7,431.3,17.5l0,0c56-11.5,114.5-9.7,169.5,5.1l0,0
    c254.9,68.7,527.3,68.7,782.2,0.1l21.9-5.9c41.2-11.1,84.7-13.8,127.2-7.9l0,0c128.7,17.8,260.1,14.8,387.6-8.9l0,0V1080.2z"/>
  </svg>
  <!-- FOG 2 -->
  <svg version="1.1" class="fog-2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 1920 1080" xml:space="preserve">
  <style type="text/css">
    .st0{fill:url(#SVGID_1_);}
  </style>
  <linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="959.5" y1="1080" x2="959.5" y2="243.8783">
    <stop  offset="0" style="stop-color:#F4DBDD"/>
    <stop  offset="1" style="stop-color:#F9F7F9"/>
  </linearGradient>
  <path class="st0" d="M1920,1080H-1V243.9l225.1,64.9c156.3,45,321.7,57.2,483.9,35.5l126.4-16.9c244.9-32.7,568.9,39.2,738.6-0.9
    s0,0,0,0s0,0,0,0l346.9-82.6V1080z"/>
  </svg>
  <!-- GET HELP BUTTON -->
  <div class="text-center">
      <%= link_to "Get Help", get_help_path, class: "charlies-btn-homepage hidden", id: "gethelp" %>
  </div>

</div>

app/views/pages/settings.html.erb
<div class="title"><h1>Set your calmness</h1></div>
<div class="container settings">
  <div class="accordion" id="accordionMain">
    <div class="card">
      <div class="card-header" id="headingOne">
        <h5 class="mb-0">
          <button class="btn" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            Contacts
          </button>
        </h5>
      </div>
      <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionMain">
        <div class="card-body">
            <div class="accordion" id="accordion2">
              <% @contacts.each do |contact| %>
                <div class="card">
                  <div class="card-header" id="heading<%= contact.id %>">
                    <h5 class="mb-0">
                      <button class="btn" type="button" data-toggle="collapse" data-target="#collapse<%= contact.id %>" aria-expanded="false" aria-controls="collapse<%= contact.id %>">
                        <%= contact.name == "" ? "Empty" : contact.name %>
                      </button>
                    </h5>
                  </div>
                  <div id="collapse<%= contact.id %>" class="collapse" aria-labelledby="heading<%= contact.id %>" data-parent="#accordion2">
                    <div class="card-body">
                      <%= simple_form_for contact do |f| %>
                        <%= f.input :name, placeholder: "Enter a name" %>
                        <%= f.input :phone_number, placeholder: "Enter a phone number" %>
                        <%= f.button :submit, class:"beautiful-btn" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="headingTwo">
        <h5 class="mb-0">
          <button class="btn collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Message
          </button>
        </h5>
      </div>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionMain">
        <div class="card-body">
          <%= render "shared/message", resource: current_user %>
        </div>
      </div>
    </div>
  </div>
    <div class="card card-header" id="toggleswitch<%= current_user.voice %>">
      <div id="toggle<%= current_user.voice %>"><%= link_to "Sound #{current_user.voice ? "on" : "off"}", toggle_path, method: :post %></div>
    </div>
  <div class="mini-btn"><%= link_to "Back", dashboard_path %></div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-3" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-3" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<ul class="footer-list">
  <li>
<!-- Generator: Adobe Illustrator 25.0.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<%= link_to root_path do %>
<svg width="35" height="35" viewBox="0 0 35 35" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M17.6066 27.4231C19.1605 27.4231 20.4203 26.151 20.4203 24.5818C20.4203 23.0126 19.1605 21.7405 17.6066 21.7405C16.0527 21.7405 14.793 23.0126 14.793 24.5818C14.793 26.151 16.0527 27.4231 17.6066 27.4231Z" fill="#FE776B"/>
<path d="M33.039 18.9852C34.1221 18.9852 35 18.0986 35 17.0049C35 15.9112 34.1221 15.0246 33.039 15.0246C31.956 15.0246 31.078 15.9112 31.078 17.0049C31.078 18.0986 31.956 18.9852 33.039 18.9852Z" fill="#FE776B"/>
<path d="M24.5128 14.2066C25.5958 14.2066 26.4738 13.32 26.4738 12.2263C26.4738 11.1326 25.5958 10.246 24.5128 10.246C23.4297 10.246 22.5518 11.1326 22.5518 12.2263C22.5518 13.32 23.4297 14.2066 24.5128 14.2066Z" fill="#FE776B"/>
<path d="M17.9049 10.246C18.8231 10.246 19.5675 9.49431 19.5675 8.56704C19.5675 7.63977 18.8231 6.88807 17.9049 6.88807C16.9867 6.88807 16.2423 7.63977 16.2423 8.56704C16.2423 9.49431 16.9867 10.246 17.9049 10.246Z" fill="#FE776B"/>
<path d="M25.4081 4.39114C26.1144 4.39114 26.687 3.81291 26.687 3.09963C26.687 2.38635 26.1144 1.80812 25.4081 1.80812C24.7017 1.80812 24.1292 2.38635 24.1292 3.09963C24.1292 3.81291 24.7017 4.39114 25.4081 4.39114Z" fill="#FE776B"/>
<path d="M18.1181 2.15252C18.7067 2.15252 19.1839 1.67066 19.1839 1.07626C19.1839 0.481858 18.7067 0 18.1181 0C17.5295 0 17.0524 0.481858 17.0524 1.07626C17.0524 1.67066 17.5295 2.15252 18.1181 2.15252Z" fill="#FE776B"/>
<path d="M31.3762 10.2891C32.2945 10.2891 33.0388 9.53735 33.0388 8.61009C33.0388 7.68282 32.2945 6.93112 31.3762 6.93112C30.458 6.93112 29.7136 7.68282 29.7136 8.61009C29.7136 9.53735 30.458 10.2891 31.3762 10.2891Z" fill="#FE776B"/>
<path d="M31.078 26.7774C32.632 26.7774 33.8917 25.5053 33.8917 23.936C33.8917 22.3668 32.632 21.0947 31.078 21.0947C29.5241 21.0947 28.2644 22.3668 28.2644 23.936C28.2644 25.5053 29.5241 26.7774 31.078 26.7774Z" fill="#FE776B"/>
<path d="M4.68937 26.7774C6.24331 26.7774 7.50302 25.5053 7.50302 23.936C7.50302 22.3668 6.24331 21.0947 4.68937 21.0947C3.13544 21.0947 1.87573 22.3668 1.87573 23.936C1.87573 25.5053 3.13544 26.7774 4.68937 26.7774Z" fill="#FE776B"/>
<path d="M25.2376 32.8905C26.7915 32.8905 28.0512 31.6184 28.0512 30.0492C28.0512 28.48 26.7915 27.2079 25.2376 27.2079C23.6837 27.2079 22.424 28.48 22.424 30.0492C22.424 31.6184 23.6837 32.8905 25.2376 32.8905Z" fill="#FE776B"/>
<path d="M10.2315 32.8905C11.7854 32.8905 13.0451 31.6184 13.0451 30.0492C13.0451 28.48 11.7854 27.2079 10.2315 27.2079C8.67756 27.2079 7.41785 28.48 7.41785 30.0492C7.41785 31.6184 8.67756 32.8905 10.2315 32.8905Z" fill="#FE776B"/>
<path d="M11.1694 23.2042C12.7233 23.2042 13.983 21.9321 13.983 20.3628C13.983 18.7936 12.7233 17.5215 11.1694 17.5215C9.61542 17.5215 8.35571 18.7936 8.35571 20.3628C8.35571 21.9321 9.61542 23.2042 11.1694 23.2042Z" fill="#FE776B"/>
<path d="M11.1694 15.0677C12.7233 15.0677 13.983 13.7955 13.983 12.2263C13.983 10.6571 12.7233 9.38499 11.1694 9.38499C9.61542 9.38499 8.35571 10.6571 8.35571 12.2263C8.35571 13.7955 9.61542 15.0677 11.1694 15.0677Z" fill="#FE776B"/>
<path d="M2.81364 18.9852C4.36757 18.9852 5.62728 17.7131 5.62728 16.1439C5.62728 14.5747 4.36757 13.3026 2.81364 13.3026C1.25971 13.3026 0 14.5747 0 16.1439C0 17.7131 1.25971 18.9852 2.81364 18.9852Z" fill="#FE776B"/>
<path d="M4.68937 11.6236C6.24331 11.6236 7.50302 10.3515 7.50302 8.78229C7.50302 7.21307 6.24331 5.94096 4.68937 5.94096C3.13544 5.94096 1.87573 7.21307 1.87573 8.78229C1.87573 10.3515 3.13544 11.6236 4.68937 11.6236Z" fill="#FE776B"/>
<path d="M10.2315 5.94096C11.7854 5.94096 13.0451 4.66885 13.0451 3.09963C13.0451 1.53041 11.7854 0.258301 10.2315 0.258301C8.67756 0.258301 7.41785 1.53041 7.41785 3.09963C7.41785 4.66885 8.67756 5.94096 10.2315 5.94096Z" fill="#FE776B"/>
<path d="M24.5127 23.2042C26.0667 23.2042 27.3264 21.9321 27.3264 20.3628C27.3264 18.7936 26.0667 17.5215 24.5127 17.5215C22.9588 17.5215 21.6991 18.7936 21.6991 20.3628C21.6991 21.9321 22.9588 23.2042 24.5127 23.2042Z" fill="#FE776B"/>
<path d="M17.6066 35C19.1605 35 20.4203 33.7279 20.4203 32.1587C20.4203 30.5895 19.1605 29.3173 17.6066 29.3173C16.0527 29.3173 14.793 30.5895 14.793 32.1587C14.793 33.7279 16.0527 35 17.6066 35Z" fill="#FE776B"/>
<path d="M17.6066 19.8462C19.1605 19.8462 20.4203 18.5741 20.4203 17.0049C20.4203 15.4357 19.1605 14.1636 17.6066 14.1636C16.0527 14.1636 14.793 15.4357 14.793 17.0049C14.793 18.5741 16.0527 19.8462 17.6066 19.8462Z" fill="#FE776B"/>
</svg>
<% end %>
</li>
  <li>
<!-- Generator: Adobe Illustrator 25.0.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<%= link_to dashboard_path do %>
<svg version="1.1" id="Ebene_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 500 500" xml:space="preserve">
<g>
  <path d="M76.5,4C42.6,4,15,31.5,15,65.4s27.6,61.5,61.5,61.5S138,99.4,138,65.4S110.4,4,76.5,4z M76.5,99.4c-18.7,0-34-15.2-34-34
    s15.2-34,34-34s34,15.2,34,34S95.2,99.4,76.5,99.4z"/>
  <path d="M76.5,188.5C42.6,188.5,15,216.1,15,250s27.6,61.5,61.5,61.5S138,283.9,138,250S110.4,188.5,76.5,188.5z M76.5,284
    c-18.7,0-34-15.2-34-34s15.2-34,34-34s34,15.2,34,34S95.2,284,76.5,284z"/>
  <path d="M76.5,373.1c-33.9,0-61.5,27.6-61.5,61.5S42.6,496,76.5,496s61.5-27.6,61.5-61.5S110.4,373.1,76.5,373.1z M76.5,468.5
    c-18.7,0-34-15.2-34-34c0-18.7,15.2-34,34-34s34,15.2,34,34C110.5,453.3,95.2,468.5,76.5,468.5z"/>
  <path d="M250,4c-33.9,0-61.5,27.6-61.5,61.5s27.6,61.5,61.5,61.5s61.5-27.6,61.5-61.5S283.9,4,250,4z M250,99.4
    c-18.7,0-34-15.2-34-34s15.2-34,34-34s34,15.2,34,34S268.7,99.4,250,99.4z"/>
  <path d="M250,188.5c-33.9,0-61.5,27.6-61.5,61.5s27.6,61.5,61.5,61.5s61.5-27.6,61.5-61.5S283.9,188.5,250,188.5z M250,284
    c-18.7,0-34-15.2-34-34s15.2-34,34-34s34,15.2,34,34S268.7,284,250,284z"/>
  <path d="M250,373.1c-33.9,0-61.5,27.6-61.5,61.5S216.1,496,250,496s61.5-27.6,61.5-61.5S283.9,373.1,250,373.1z M250,468.5
    c-18.7,0-34-15.2-34-34c0-18.7,15.2-34,34-34s34,15.2,34,34C284,453.3,268.7,468.5,250,468.5z"/>
  <path d="M423.5,4C389.6,4,362,31.5,362,65.4s27.6,61.5,61.5,61.5S485,99.4,485,65.4S457.4,4,423.5,4z M423.5,99.4
    c-18.7,0-34-15.2-34-34s15.2-34,34-34c18.7,0,34,15.2,34,34S442.2,99.4,423.5,99.4z"/>
  <path d="M423.5,188.5c-33.9,0-61.5,27.6-61.5,61.5s27.6,61.5,61.5,61.5S485,283.9,485,250S457.4,188.5,423.5,188.5z M423.5,284
    c-18.7,0-34-15.2-34-34s15.2-34,34-34c18.7,0,34,15.2,34,34S442.2,284,423.5,284z"/>
  <path d="M423.5,373.1c-33.9,0-61.5,27.6-61.5,61.5s27.6,61.5,61.5,61.5s61.5-27.6,61.5-61.5S457.4,373.1,423.5,373.1z M423.5,468.5
    c-18.7,0-34-15.2-34-34c0-18.7,15.2-34,34-34c18.7,0,34,15.2,34,34C457.5,453.3,442.2,468.5,423.5,468.5z"/>
</g>
</svg>
<% end %>
</li>
</ul>

app/views/shared/_message.html.erb
<%= simple_form_for message_path, method: :patch do |f| %>
  <%= f.input :message, as: :text, placeholder: "#{current_user.message}" %>
  <%= f.submit "Save", id: "msg-save-btn" %>
<% end %>